import os
from pathlib import Path

def c(p):
    Path(p).parent.mkdir(parents=True, exist_ok=True)
    Path(p).touch()

def d(p):
    Path(p).mkdir(parents=True, exist_ok=True)

def w(p, t):
    Path(p).parent.mkdir(parents=True, exist_ok=True)
    Path(p).write_text(t)

r = Path('ex-machina')
r.mkdir(exist_ok=True)
os.chdir(r)

w('README.md', '# Ex Machina\n\nMinuat Inutilia\n')
w('LICENSE', 'Proprietary License\nAll Rights Reserved\n')
w('.gitignore', '*.pyc\n__pycache__/\ntarget/\n.env\n*.log\nnode_modules/\n.DS_Store\n')
w('docker-compose.yml', 'version: "3.9"\nservices:\n  postgres:\n    image: postgres:15\n  redis:\n    image: redis:7\n  kafka:\n    image: confluentinc/cp-kafka:7.5.0\n')

d('kubernetes/services')
c('kubernetes/namespace.yaml')
c('kubernetes/ingress.yaml')
c('kubernetes/services/sieo-deployment.yaml')
c('kubernetes/services/sioo-deployment.yaml')
c('kubernetes/services/sifo-deployment.yaml')
c('kubernetes/services/sito-deployment.yaml')

w('brain/foundation/model/architecture.py', 'from torch import nn\n')
w('brain/foundation/model/config.yaml', 'model_size: large\n')
d('brain/foundation/model/checkpoint')
w('brain/foundation/training/pretrain.py', 'import torch\n')
w('brain/foundation/training/continual_learning.py', 'import torch\n')
d('brain/foundation/training/datasets')
w('brain/foundation/inference/engine.py', 'class BrainInferenceEngine:\n    pass\n')
w('brain/foundation/inference/distributed.py', 'import torch.distributed as dist\n')

w('brain/memory/episodic/storage.rs', 'use serde::{{Serialize, Deserialize}};\n')
w('brain/memory/episodic/retrieval.rs', 'use serde::{{Serialize, Deserialize}};\n')
w('brain/memory/semantic/vector_db.py', 'import pinecone\n')
w('brain/memory/semantic/knowledge_graph.py', 'import neo4j\n')
w('brain/memory/working/context_manager.rs', 'use std::collections::HashMap;\n')

d('brain/cortices/sieo/lora_weights')
d('brain/cortices/sieo/prompt_templates')
w('brain/cortices/sieo/fine_tune_config.yaml', 'base_model: ex-machina-foundation-v1\nadapter_type: lora\nrank: 32\n')
d('brain/cortices/sioo/lora_weights')
d('brain/cortices/sioo/prompt_templates')
w('brain/cortices/sioo/fine_tune_config.yaml', 'base_model: ex-machina-foundation-v1\n')
d('brain/cortices/sifo/lora_weights')
d('brain/cortices/sifo/prompt_templates')
w('brain/cortices/sifo/fine_tune_config.yaml', 'base_model: ex-machina-foundation-v1\n')
d('brain/cortices/sito/lora_weights')
d('brain/cortices/sito/prompt_templates')
w('brain/cortices/sito/fine_tune_config.yaml', 'base_model: ex-machina-foundation-v1\n')

w('brain/synapse/attention_router.py', 'class SynapseRouter:\n    pass\n')
w('brain/synapse/signal_processor.rs', 'pub struct SignalProcessor;\n')
w('brain/synapse/coherence_manager.py', 'class CoherenceManager:\n    pass\n')

w('brain/consciousness/self_monitor.py', 'class SelfMonitor:\n    pass\n')
w('brain/consciousness/uncertainty_quantifier.py', 'class UncertaintyQuantifier:\n    pass\n')
w('brain/consciousness/override_handler.py', 'class OverrideHandler:\n    pass\n')

w('services/sieo/Cargo.toml', '[package]\nname = "sieo"\nversion = "0.1.0"\nedition = "2021"\n')
w('services/sieo/Dockerfile', 'FROM rust:1.75\nWORKDIR /app\n')
w('services/sieo/src/main.rs', 'fn main() {}\n')
w('services/sieo/src/lib.rs', 'pub mod api;\npub mod core;\n')
w('services/sieo/src/api/mod.rs', 'pub mod routes;\npub mod handlers;\n')
c('services/sieo/src/api/routes.rs')
c('services/sieo/src/api/handlers.rs')
w('services/sieo/src/core/mod.rs', 'pub mod strategy;\npub mod decision_engine;\npub mod reasoning;\n')
c('services/sieo/src/core/strategy.rs')
c('services/sieo/src/core/decision_engine.rs')
c('services/sieo/src/core/reasoning.rs')
w('services/sieo/src/models/mod.rs', 'pub mod decision;\npub mod strategy;\n')
c('services/sieo/src/models/decision.rs')
c('services/sieo/src/models/strategy.rs')
w('services/sieo/src/utils/mod.rs', 'pub mod logger;\n')
c('services/sieo/src/utils/logger.rs')
c('services/sieo/tests/integration_tests.rs')
c('services/sieo/tests/unit_tests.rs')

w('services/sioo/Cargo.toml', '[package]\nname = "sioo"\nversion = "0.1.0"\nedition = "2021"\n')
w('services/sioo/Dockerfile', 'FROM rust:1.75\nWORKDIR /app\n')
w('services/sioo/src/main.rs', 'fn main() {}\n')
w('services/sioo/src/lib.rs', 'pub mod api;\npub mod core;\n')
w('services/sioo/src/api/mod.rs', 'pub mod routes;\n')
c('services/sioo/src/api/routes.rs')
w('services/sioo/src/core/mod.rs', 'pub mod process_optimizer;\npub mod workflow_engine;\npub mod resource_allocator;\n')
c('services/sioo/src/core/process_optimizer.rs')
c('services/sioo/src/core/workflow_engine.rs')
c('services/sioo/src/core/resource_allocator.rs')
d('services/sioo/src/models')
d('services/sioo/src/utils')
d('services/sioo/tests')

w('services/sifo/pyproject.toml', '[project]\nname = "sifo"\nversion = "0.1.0"\n')
w('services/sifo/Dockerfile', 'FROM python:3.11\nWORKDIR /app\n')
w('services/sifo/requirements.txt', 'fastapi\nuvicorn\npandas\nnumpy\n')
w('services/sifo/src/__init__.py', '')
w('services/sifo/src/main.py', 'from fastapi import FastAPI\napp = FastAPI()\n')
w('services/sifo/src/api/__init__.py', '')
c('services/sifo/src/api/routes.py')
c('services/sifo/src/api/handlers.py')
w('services/sifo/src/core/__init__.py', '')
c('services/sifo/src/core/financial_modeling.py')
c('services/sifo/src/core/risk_analysis.py')
c('services/sifo/src/core/budget_optimizer.py')
c('services/sifo/src/core/forecasting.py')
w('services/sifo/src/models/__init__.py', '')
c('services/sifo/src/models/transaction.py')
c('services/sifo/src/models/budget.py')
w('services/sifo/src/utils/__init__.py', '')
c('services/sifo/src/utils/logger.py')
d('services/sifo/tests')
c('services/sifo/tests/test_financial_modeling.py')
c('services/sifo/tests/test_budget_optimizer.py')

w('services/sito/Cargo.toml', '[package]\nname = "sito"\nversion = "0.1.0"\nedition = "2021"\n')
w('services/sito/Dockerfile', 'FROM rust:1.75\nWORKDIR /app\n')
w('services/sito/src/main.rs', 'fn main() {}\n')
w('services/sito/src/lib.rs', 'pub mod api;\npub mod core;\n')
d('services/sito/src/api')
w('services/sito/src/core/mod.rs', 'pub mod infrastructure_optimizer;\npub mod security_monitor;\npub mod performance_analyzer;\npub mod system_architect;\n')
c('services/sito/src/core/infrastructure_optimizer.rs')
c('services/sito/src/core/security_monitor.rs')
c('services/sito/src/core/performance_analyzer.rs')
c('services/sito/src/core/system_architect.rs')
d('services/sito/src/models')
d('services/sito/src/utils')
d('services/sito/tests')

w('services/clo/pyproject.toml', '[project]\nname = "clo"\nversion = "0.1.0"\n')
w('services/clo/Dockerfile', 'FROM python:3.11\nWORKDIR /app\n')
w('services/clo/requirements.txt', 'fastapi\nuvicorn\n')
w('services/clo/src/__init__.py', '')
w('services/clo/src/main.py', 'from fastapi import FastAPI\napp = FastAPI()\n')
w('services/clo/src/core/__init__.py', '')
c('services/clo/src/core/truth_validator.py')
c('services/clo/src/core/reasoning_auditor.py')
c('services/clo/src/core/logic_checker.py')
c('services/clo/src/core/hallucination_detector.py')
d('services/clo/src/models')
d('services/clo/tests')

w('services/gateway/Cargo.toml', '[package]\nname = "gateway"\nversion = "0.1.0"\nedition = "2021"\n')
w('services/gateway/Dockerfile', 'FROM rust:1.75\nWORKDIR /app\n')
w('services/gateway/src/main.rs', 'fn main() {}\n')
c('services/gateway/src/routing.rs')
w('services/gateway/src/auth/mod.rs', 'pub mod middleware;\n')
c('services/gateway/src/auth/middleware.rs')
c('services/gateway/src/rate_limiting.rs')
c('services/gateway/src/load_balancer.rs')
d('services/gateway/tests')

w('services/orchestrator/pyproject.toml', '[project]\nname = "orchestrator"\nversion = "0.1.0"\n')
w('services/orchestrator/Dockerfile', 'FROM python:3.11\nWORKDIR /app\n')
w('services/orchestrator/requirements.txt', 'fastapi\nuvicorn\n')
w('services/orchestrator/src/__init__.py', '')
w('services/orchestrator/src/main.py', 'from fastapi import FastAPI\napp = FastAPI()\n')
w('services/orchestrator/src/core/__init__.py', '')
c('services/orchestrator/src/core/task_coordinator.py')
c('services/orchestrator/src/core/decision_aggregator.py')
c('services/orchestrator/src/core/conflict_resolver.py')
c('services/orchestrator/src/core/workflow_manager.py')
d('services/orchestrator/src/models')
d('services/orchestrator/tests')

w('services/synapse-broker/Cargo.toml', '[package]\nname = "synapse-broker"\nversion = "0.1.0"\nedition = "2021"\n')
w('services/synapse-broker/src/main.rs', 'fn main() {}\n')
c('services/synapse-broker/src/event_validator.rs')
c('services/synapse-broker/src/pattern_matcher.rs')
c('services/synapse-broker/src/feedback_tracker.rs')

w('services/synapse-analytics/pyproject.toml', '[project]\nname = "synapse-analytics"\nversion = "0.1.0"\n')
w('services/synapse-analytics/src/__init__.py', '')
c('services/synapse-analytics/src/cross_executive_learning.py')
c('services/synapse-analytics/src/convergence_tracker.py')
c('services/synapse-analytics/src/anomaly_detector.py')

w('shared/rust/common/Cargo.toml', '[package]\nname = "common"\nversion = "0.1.0"\nedition = "2021"\n')
w('shared/rust/common/src/lib.rs', 'pub mod error;\npub mod config;\npub mod types;\n')
c('shared/rust/common/src/error.rs')
c('shared/rust/common/src/config.rs')
c('shared/rust/common/src/types.rs')

w('shared/rust/messaging/Cargo.toml', '[package]\nname = "messaging"\nversion = "0.1.0"\nedition = "2021"\n')
w('shared/rust/messaging/src/lib.rs', 'pub mod kafka;\npub mod rabbitmq;\n')
c('shared/rust/messaging/src/kafka.rs')
c('shared/rust/messaging/src/rabbitmq.rs')

w('shared/rust/database/Cargo.toml', '[package]\nname = "database"\nversion = "0.1.0"\nedition = "2021"\n')
w('shared/rust/database/src/lib.rs', 'pub mod postgres;\npub mod redis;\n')
c('shared/rust/database/src/postgres.rs')
c('shared/rust/database/src/redis.rs')

w('shared/rust/synapse/Cargo.toml', '[package]\nname = "synapse"\nversion = "0.1.0"\nedition = "2021"\n')
w('shared/rust/synapse/src/lib.rs', 'pub mod event;\npub mod publisher;\npub mod subscriber;\n')
c('shared/rust/synapse/src/event.rs')
c('shared/rust/synapse/src/publisher.rs')
c('shared/rust/synapse/src/subscriber.rs')

w('shared/python/common/pyproject.toml', '[project]\nname = "common"\nversion = "0.1.0"\n')
w('shared/python/common/src/__init__.py', '')
c('shared/python/common/src/error.py')
c('shared/python/common/src/config.py')
c('shared/python/common/src/types.py')

w('shared/python/messaging/pyproject.toml', '[project]\nname = "messaging"\nversion = "0.1.0"\n')
w('shared/python/messaging/src/__init__.py', '')
c('shared/python/messaging/src/kafka_client.py')

w('shared/python/database/pyproject.toml', '[project]\nname = "database"\nversion = "0.1.0"\n')
w('shared/python/database/src/__init__.py', '')
c('shared/python/database/src/postgres_client.py')

w('shared/python/synapse/pyproject.toml', '[project]\nname = "synapse"\nversion = "0.1.0"\n')
w('shared/python/synapse/src/__init__.py', '')
c('shared/python/synapse/src/event.py')
c('shared/python/synapse/src/publisher.py')
c('shared/python/synapse/src/subscriber.py')

w('infrastructure/terraform/main.tf', 'terraform {\n  required_version = ">= 1.0"\n}\n')
w('infrastructure/terraform/variables.tf', 'variable "env" {\n  type = string\n}\n')
d('infrastructure/terraform/modules/eks')
d('infrastructure/terraform/modules/rds')
d('infrastructure/terraform/modules/redis')
d('infrastructure/terraform/environments/dev')
d('infrastructure/terraform/environments/staging')
d('infrastructure/terraform/environments/prod')

d('infrastructure/ansible/playbooks')
d('infrastructure/ansible/roles')

d('ml/models/sieo_strategy_model')
d('ml/models/sifo_forecasting_model')
d('ml/models/clo_reasoning_model')
w('ml/training/train_sieo.py', 'import torch\n')
w('ml/training/train_sifo.py', 'import torch\n')
w('ml/training/requirements.txt', 'torch\ntransformers\n')
d('ml/notebooks')
c('ml/notebooks/exploratory_analysis.ipynb')

w('monitoring/prometheus/prometheus.yml', 'global:\n  scrape_interval: 15s\n')
d('monitoring/grafana/dashboards')
d('monitoring/alerting')
c('monitoring/alerting/rules.yml')

d('docs/architecture')
w('docs/architecture/overview.md', '# Architecture Overview\n')
w('docs/architecture/service-communication.md', '# Service Communication\n')
w('docs/architecture/data-flow.md', '# Data Flow\n')
d('docs/api')
w('docs/api/sieo.md', '# SIEO API\n')
w('docs/api/sioo.md', '# SIOO API\n')
w('docs/api/sifo.md', '# SIFO API\n')
w('docs/api/sito.md', '# SITO API\n')
d('docs/deployment')
w('docs/deployment/getting-started.md', '# Getting Started\n')

w('scripts/setup.sh', '#!/bin/bash\necho "Setting up Ex Machina..."\n')
w('scripts/deploy.sh', '#!/bin/bash\necho "Deploying Ex Machina..."\n')
w('scripts/test-all.sh', '#!/bin/bash\necho "Running all tests..."\n')
w('scripts/build-all.sh', '#!/bin/bash\necho "Building all services..."\n')

os.chmod('scripts/setup.sh', 0o755)
os.chmod('scripts/deploy.sh', 0o755)
os.chmod('scripts/test-all.sh', 0o755)
os.chmod('scripts/build-all.sh', 0o755)

d('.github/workflows')
w('.github/workflows/ci-rust.yml', 'name: Rust CI\non: [push]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n')
w('.github/workflows/ci-python.yml', 'name: Python CI\non: [push]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n')
w('.github/workflows/deploy-dev.yml', 'name: Deploy Dev\non: [push]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n')
w('.github/workflows/deploy-prod.yml', 'name: Deploy Prod\non: [workflow_dispatch]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n')

print("✓ Ex Machina scaffolded successfully")
print(f"✓ Root: {r.absolute()}")
print("✓ Run 'cd ex-machina' to enter project")
